import { GuessPeopleCategoryEnum } from './guess.enum'

export const GuessPeopleData = [
    /* 가수 */
    { category: GuessPeopleCategoryEnum.SINGER, name: '소수빈' },
    { category: GuessPeopleCategoryEnum.SINGER, name: '탑현' },
    { category: GuessPeopleCategoryEnum.SINGER, name: '홍이삭' },

    /* 방송인 */
    { category: GuessPeopleCategoryEnum.ENTERTAINER, name: '유재석' },
    { category: GuessPeopleCategoryEnum.ENTERTAINER, name: '주우재' },

    /* 배우 */
    { category: GuessPeopleCategoryEnum.ACTOR, name: '공유' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '박보검' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '박은빈' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '박정민' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '송중기' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '송하윤' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '신혜선' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '지창욱' },
    { category: GuessPeopleCategoryEnum.ACTOR, name: '최현욱' },

    /* 아이돌 */
    { category: GuessPeopleCategoryEnum.IDOL, name: '뉴진스 다니엘' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '뉴진스 민지' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '뉴진스 하니' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '뉴진스 해린' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '뉴진스 혜인' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 서현' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 수영' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 써니' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 유리' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 윤아' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 태연' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 티파니' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '소녀시대 효연' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '아이브 가을' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '아이브 레이' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '아이브 리즈' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '아이브 안유진' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '아이브 이서' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '아이브 장원영' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 나연' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 다현' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 모모' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 미나' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 사나' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 정연' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 지효' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 쯔위' },
    { category: GuessPeopleCategoryEnum.IDOL, name: '트와이스 채영' },

    /* 야구선수 */
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 강태율' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 고승민' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 구승민' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 김도규' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 김민석' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 김상수' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 김원중' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 김진욱' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 나균안' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 노진혁' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 박세웅' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 박승욱' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 신윤후' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 안권수' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 유강남' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 윤동희' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 윤성빈' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 이민석' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 이인복' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 이정훈' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 이태연' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 이학주' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 장두성' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 잭 렉스' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 전준우' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 정보근' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 정성종' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 정훈' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 지시완' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 진승현' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 찰리 반즈' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 최준용' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 한동희' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 한현희' },
    { category: GuessPeopleCategoryEnum.BASEBALL, name: '롯데자이언츠 황성빈' }
]
