import { GuessCharacterCategoryEnum } from './guess.enum'

export const GuessCharacterData = [
    /* 날아라호빵맨 */
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '딸랑이' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '롤빵소녀' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '메론빵소녀' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '버터누나' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '세균맨' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '식빵맨' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '잼아저씨' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '짤랑이' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '치즈' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '카레빵맨' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '크림판다' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '해골맨' },
    { category: GuessCharacterCategoryEnum.ANPANMAN, name: '호빵맨' },

    /* 네모바지스폰지밥 */
    { category: GuessCharacterCategoryEnum.SPONGEBOB, name: '다람이' },
    { category: GuessCharacterCategoryEnum.SPONGEBOB, name: '뚱이' },
    { category: GuessCharacterCategoryEnum.SPONGEBOB, name: '스폰지밥' },
    { category: GuessCharacterCategoryEnum.SPONGEBOB, name: '집게사장' },
    { category: GuessCharacterCategoryEnum.SPONGEBOB, name: '징징이' },
    { category: GuessCharacterCategoryEnum.SPONGEBOB, name: '플랑크톤' },
    { category: GuessCharacterCategoryEnum.SPONGEBOB, name: '핑핑이' },

    /* 도라에몽 */
    { category: GuessCharacterCategoryEnum.DORAEMON, name: '도라미' },
    { category: GuessCharacterCategoryEnum.DORAEMON, name: '도라에몽' },
    { category: GuessCharacterCategoryEnum.DORAEMON, name: '비실이' },
    { category: GuessCharacterCategoryEnum.DORAEMON, name: '이슬이' },
    { category: GuessCharacterCategoryEnum.DORAEMON, name: '진구' },
    { category: GuessCharacterCategoryEnum.DORAEMON, name: '퉁퉁이' },

    /* 디즈니프린세스 */
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '라야' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '라푼젤' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '메리다' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '모아나' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '뮬란' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '백설공주' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '벨' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '신데렐라' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '에리얼' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '오로라' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '자스민' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '티아나' },
    { category: GuessCharacterCategoryEnum.DISNEYPRINCESS, name: '포카혼타스' },

    /* 명탐정코난 */
    { category: GuessCharacterCategoryEnum.CONAN, name: '고뭉치' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '골롬보반장' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '괴도키드' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '남도일' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '노애리변호사' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '박세모' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '브라운박사' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '서가영' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '신형선형사' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '양세라' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '오지인형사' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '워커' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '유명한탐정' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '유미란' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '정보라' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '진' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '코난' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '하인성' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '한아름' },
    { category: GuessCharacterCategoryEnum.CONAN, name: '홍장미' },

    /* 뽀롱뽀롱뽀로로 */
    { category: GuessCharacterCategoryEnum.PORORO, name: '로디' },
    { category: GuessCharacterCategoryEnum.PORORO, name: '루피' },
    { category: GuessCharacterCategoryEnum.PORORO, name: '뽀로로' },
    { category: GuessCharacterCategoryEnum.PORORO, name: '에디' },
    { category: GuessCharacterCategoryEnum.PORORO, name: '크롱' },
    { category: GuessCharacterCategoryEnum.PORORO, name: '패티' },
    { category: GuessCharacterCategoryEnum.PORORO, name: '포비' },
    { category: GuessCharacterCategoryEnum.PORORO, name: '해리' },

    /* 산리오 */
    { category: GuessCharacterCategoryEnum.SANRIO, name: '구데타마' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '꿈 속의 뮤' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '딩구리데이즈' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '리틀트윈스타' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '마이멜로디' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '배드바츠마루' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '숲의 요정 페어리루' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '시나모롤' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '어그레츠코' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '케로케로케로피' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '코기뮹' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '쿠로미' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '턱시도샘' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '포차코' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '폼폼푸린' },
    { category: GuessCharacterCategoryEnum.SANRIO, name: '헬로키티' },

    /* 원피스 */
    { category: GuessCharacterCategoryEnum.ONEPIECE, name: '나미' },
    { category: GuessCharacterCategoryEnum.ONEPIECE, name: '루피' },
    { category: GuessCharacterCategoryEnum.ONEPIECE, name: '상디' },
    { category: GuessCharacterCategoryEnum.ONEPIECE, name: '우솝' },
    { category: GuessCharacterCategoryEnum.ONEPIECE, name: '조로' },
    { category: GuessCharacterCategoryEnum.ONEPIECE, name: '쵸파' },

    /* 짱구는못말려 */
    { category: GuessCharacterCategoryEnum.CRAYON, name: '나미리선생님' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '맹구' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '봉미선' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '수지' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '신형만' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '원장선생님' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '유리' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '짱구' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '짱아' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '차은주선생님' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '채성아선생님' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '철수' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '훈이' },
    { category: GuessCharacterCategoryEnum.CRAYON, name: '흰둥이' },

    /* 포켓몬스터 */
    { category: GuessCharacterCategoryEnum.POKEMON, name: '강챙이' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '거북왕' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '고라파덕' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '고지' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '골덕' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '괴력몬' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '구구' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '근육몬' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '꼬부기' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '나옹' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '냄새꼬' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '닥트리오' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '단데기' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '디그다' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '뚜벅쵸' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '라이츄' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '라플레시아' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '리자드' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '리자몽' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '망나뇽' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '메타몽' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '모다피' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '모래두지' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '미뇽' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '발챙이' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '버터플' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '삐' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '삐삐' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '샤미드' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '슈룩챙이' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '시드라' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '신뇽' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '쏘드라' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '아보' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '아보크' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '알통몬' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '야도란' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '야돈' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '어니부기' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '우츠동' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '우츠보트' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '이브이' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '이상해꽃' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '이상해씨' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '이상해풀' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '잠만보' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '캐터피' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '킹드라' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '탕구리' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '텅구리' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '파이리' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '페르시온' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '푸린' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '푸크린' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '푸푸린' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '피존투' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '피죤' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '피카츄' },
    { category: GuessCharacterCategoryEnum.POKEMON, name: '픽시' }
]
